# Generated by Django 5.2 on 2026-05-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
